---
title: "What's Wrong with WAR?"
description: |
  A short description of the post.

date: 12-15-2020
output:
  distill::distill_article:
    self_contained: false
---

Ask just about anyone and they will tell you that the most important thing is sports is winning. Of course, individual awards are always on certain players’ radars (whether they admit it or not), but fans, managers, and owners are primarily invested in maximizing team W’s. The recent explosion of sports analytics has given rise to a countless number of formulas, ratings, and “advanced metrics” that claim to perfectly measure individual performance, but how do these stats translate to actual team performance?

## WAR in Baseball

Baseball’s WAR (Wins Above Replacement) has risen to become one of the most widely used advanced metrics across all of sports. Different websites have slightly different ways to calculate WAR, but each essentially defines it as a measure of how much value a player provides to his team relative to the average “replacement” player. For the purpose of this article, I will focus specifically on Baseball Reference’s version because I feel most loyal to their site. I won’t go into too much detail about exactly what it is and how its calculated, so if you want to read more, you can here. 

Hundreds of factors go into measuring WAR from batting stats to fielding stats to baserunning stats to positional adjustments to seasonal run environment adjustments. Sabermetricians have spent the past decade tweaking the stat to make it more and more precise, and it’s popularity has steadily risen as it has made its way onto ESPN broadcasts, official MLB tweets, and ballpark scoreboards. Today, WAR is a central part of even the casual fan’s vocabulary and some regard it as baseball’s perfect catch-all stat. But is it? The short answer is no. Let’s take a look at some of the reasons why.

## Luck

Luck plays a massive role in every part of our lives and sports are no exception. It doesn’t take an expert to see how Franco Harris’ immaculate reception changed the course of the 1972 NFL Playoffs or more recently how the four perfect bounces on Kawhi Leonard’s game 7 lead to Joel Embiid in tears and two new Drake tracks. In baseball, luck plays an especially enormous role in every play. Rafael Devers may rip a 110 mph liner that happens to land in Justin Smoak’s glove before he even has time to blink, while in Yankee Stadium, Aaron Judge can hit a weak pop-up off the end of his bat that would be an easy out almost anywhere else and it goes down on paper as a homerun (the most valuable play in baseball). Just as batting average is susceptible to giving players credit they don’t deserve (or didn’t earn depending on how you look at it) and vice versa, WAR, which factors in a weighted version of on-base percentage, doesn’t capture which players are getting “lucky”. With this being said, the scores/results/records also give pop-ups like Aaron Judge credit and punishes lineouts like Devers’. While it might be frustrating to fans and players, luck is a fundamental part of baseball and no stat will ever be immune to it.

<font size = "2.5"> <p style="line-height:1.0 "> Note: Batting Average on Balls in Play (BABIP) is typically used to measure how “lucky” a player has been getting (and to identify whose batting average might be about to change once their sample size increases), but it still has imperfections. For example, 2018 NL MVP Christian Yelich has finished with a BABIP in the top 11 among qualifiers in 4 of his 5 complete seasons so far. This is less an indicator of him being very lucky than a sign that when he makes contact, it’s pretty hard hit. </p></font>

## Clutch?

One of the biggest criticisms of comprehensive stats like WAR is that they fail to account for the situation. There is no doubt that a three-run home run to put your team up by one in the top of the 9th is more important than a solo shot in the late innings of a blowout, but WAR treats them each the same. Does making a play in a bigger moment make someone more valuable? We are Among sports analysts, the concept of “clutch” is a frequent source of debate. Regardless of whether it exists or not, incorporating situational measures (that are out of an individual player’s control) into WAR calculations gives players on better teams or happen to have had a lot of at-bats in big situations an unfair advantage. Non-contextual measures give one standardized statistic for players across the league to be compared on. Still, if you believe in the clutch factor, the existence of WAR doesn’t mean you have to ignore a player’s .220 batting average with RISP when voting for MVP.

## Money

WAR represents the value of a player relative to the average replacement player. But if a certain player wasn’t around that doesn’t necessarily mean Joe Smith from triple A would be playing his position instead. It might if the certain player was temporarily injured (and that is what WAR should be interpreted as meaning), but baseball reference has more recently included WAA (wins above average) in many of their tables to show how a player compares to the league average. Baseball Reference explains that the issue with WAA is that a league average player is relatively expensive and is not typically bought to replace an injured starter. As seen by this definition, WAR is focusing on a player’s value healthy vs. injured. But for the free agent market, trade negotiations, and MVP voting, is this the best comparison to be making? For owners (generally speaking), baseball is a business, and that means they want to maximize performance at the lowest necessary cost. Below is a table displaying the most valuable position players of 2018 relative to their salary. 

Name	Team	WAR	Salary	Salary/WAR
Matt Chapman	OAK	8.2	$547,500	$66,728.29
Francisco Lindor	CLE	7.9	$623,200	$78,886.08
Alex Bregman	HOU	6.9	$599,000	$86,811.59
Trevor Story	COL	5.6	$555,000	$99,107.14
Whit Merrifield	KCR	5.5	$569,500	$103,545.45
Unsurprisingly, the top 5 of this list is made up of young stars that have yet to hit arbitration and are still at or near the league minimum. If we want to see how Major League front offices value WAR, the free agency market may be a better place to look. Below is a table of the most valuable position players of 2018 relative to their salary that were acquired through free agency.

Name	Team	WAR	Salary	Salary/WAR
David Peralta	ARI	3.9	$3,300,000	$846,154
Lorenzo Cain	MIL	6.9	$14,000,000	$2,028,985
Mike Moustakas	KCR/MIL	2.5	$5,500,000	$2,200,000
J.D. Martinez	BOS	6.4	$23,750,000	$3,710,938
Nick Markakis	ATL	2.6	$11,000,000	$4,230,769
To get a better sense of how the league as a whole values WAR, here is a graph displaying the relationship between 2018 WAR and average yearly salary for contracts signed in 2019 . 


r2 = 61.4%

The association between WAR and salary is fairly strong. In the 2019 market, one WAR was worth about $3.45 million on average. But what exactly does one win above replacement mean?

## So How Does it Relate to Wins?

As far as owners and fans are concerned, the only thing that matters is team performance, and team performance is measured with one very simple stat: wins. The first letter of the WAR acronym stands for “wins” so it is expected that the two are closely related. Actually, WAR is more directly measuring value added in terms of runs, not wins, but the correlation between runs and wins allows for a simple transformation for a final measurement that is true to its name. The basis of this transformation comes from baseball’s pythagorean formula: expected wins = runs scored2/(runs scored2 + runs against2). It is roughly comparable to goal difference in soccer and has similar flaws. Still, a teams actual win-loss record is typically pretty close to what would be expected based on the formula. Below are graphs showing the association of a team’s total WAR with pythagorean wins and actual wins. 



r2 = 87.24%, 94.82%

As you can see, WAR is pretty strongly associated with Pythagorean wins and only slightly less correlated with actual wins. Still, the association is not perfect (and you shouldn’t expect it to be). The outcome of a baseball game is determined by a multitude of factors regarding player performance and beyond that are not captured by WAR.

## Bill James Controversy

Ironically, the father of sabermetrics himself has been one of WAR’s biggest critics. In a 2017 article published on his personal website, Bill James gave his take on how WAR was being misused in the 2017 AL MVP argument, sending the sabermetric community into a brief period of unrest. Essentially, James’ two biggest ailments with the measure have to do with its disregard for the situation and resulting disconnect from wins. I covered the gist of the issues here, but there is plenty of further reading a quick google search away. 

## Conclusion

There is no such thing as a perfect stat. WAR is an incredible metric that captures factors of player value that no stat before has ever been able to capture and places it into one number that can be used to compare players across leagues and positions. With that being said, it also leaves out a number of factors, some of which I outlined above and others that may not even realize. When it comes to winning ball games, the team whose players have the higher combined WAR may win more often than not, but this is not always the case. The ins and outs of baseball have been quantified, analyzed, and beaten senseless by experts for decades, but there is still so much that we can’t understand let alone measure. That’s what makes it beautiful.

To be clear, I am a big proponent of WAR and use it heavily myself when assessing an MLB player’s value. Still, I think Bill James and others have made reasonable criticisms of it and advise readers to be cautious the next time it comes up as a be all end all stat in an MVP debate. 

<font size = "2.5"> <p style="line-height:1.0 "> Note: Baseball Reference released their 2020 WAR update after the completion of this article, so WAR values may now be slightly off. </p></font>